use dnf info instead of dnf info available
this gets around an issue preventing fedora repo packages from showing a description once installed to the system. otherwise, dnf info available $2 returns:

Error: No matching Packages to list